- name: Install docker package
  become: true
  become_user: root 
  package: name={{ item }} state=present
  with_items:
   - docker.io

- name: Start Docker Service
  become: true
  become_user: root
  service: name=docker state=started enabled=yes
